import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";

// แก้ไข weights -> weight และเพิ่ม subset 'latin'
const prompt = Prompt({
  subsets: ["thai"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ปรับ Type ของ children ให้เป็นมาตรฐาน Next.js
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th" className={prompt.className}>
      <body className="min-h-screen flex flex-col">{children}</body>
    </html>
  );
}